apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
  type: ClusterIP