apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: grafana-port
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
