apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: phpmyadmin
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: phpmyadmin-port
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
