apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: wordpress
spec:
  ports:
  - port: 5050
    protocol: TCP
    name: wordpress-port
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
