apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: ftps
spec:
  ports:
  - port: 21
    name: ftps-port
    targetPort: 21
  - port: 21000
    name: ftps-ports
    targetPort: 21000
  selector:
    app: ftps
  type: LoadBalancer
